### ISSUE TITLE
2019-03-27-dask-cuml.md missing info

### ISSUE THREAD

**Issue by rpanai** [dask/dask-blog#21]
The examples are on datasets of 2.8KB and 28GB or 2.8MB and 28MB?

Section Fast Fitting timing
* example 1 error is not stated
* example 2 error unit of measure is missing

**Comment by mrocklin** [comment]
cc @quasiben

**Comment by quasiben** [comment]
@rpanai thanks for the close reading!  

The diabetes data set is ~28K .  To show better performance in cuml's fitting I increased the size to `2824.0 MB` or `~28GB` in the case of hyper parameter testing the tests were done with 2.8 MB and 28 MB.

The example 1 error is not state because I only did a single measurement .  Here I'm not too concerned with errors since we are just getting a sense.  Doing repeated measurements now I see the following:

- ridge
> 597 µs ± 26.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each) 

- cuml 
> 5.46 ms ± 525 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

In terms of scale this is what the post also shows.  

I've added a PR here: https://github.com/dask/dask-blog/pull/22 to update some typos I found as well as the missing units on error.  Thank you again for your comments!
